# Generated by Django 2.2.5 on 2019-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personasdatos',
            name='edad',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterModelTable(
            name='personasdatos',
            table='datos',
        ),
    ]
